import { Barlow, Bellefair, Roboto_Condensed } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

const barlow = Barlow({
  weight: ["100", "200", "300", "400", "600", "700"],
  subsets: ["latin"],
});

const bellefair = Bellefair({
  weight: ["400"],
  subsets: ["latin"],
});

const roboto_condensed = Roboto_Condensed({
  weight: ["100","200","400", "500"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${barlow.className} ${bellefair.className}`}>
        {children}
      </body>
    </html>
  );
}
